from enum import Enum


class AuthInfoEnum(Enum):
    ERROR = 0
    CLIENT_NOT_FOUND = 1
    CLIENT_AUTH_SUCCSESS = 2
    CLIENT_AUTH_SEND_CODE = 3
    CLIENT_AUTH_WRONG = 4
    CLIENT_HASH_CODE_NOT_FOUND = 5
    CLIENT_HASH_CODE_ADDED = 6
    CLIENT_PHONE_CODE_EXPIRED = 7
    CLIENT_PASSWORD_INVALID = 8